library(shiny)

shinyUI(
  fluidPage(
  fluidRow(titlePanel(
    h1(
      img(src = "logoIMT.jpg", width = "10%"),
      img(src = "run.png", width = "8%"),
      img(src = "euromov.png", width = "12%"),
      div("ACTIMETRY", style = "color: #00ace6; font-weight: bold; line-height: 2;"),
      align = "center")
  )),
  fluidRow(wellPanel(column(width = 6,
                            selectInput(inputId = "patient",
                                        label = "Patient  choice",
                                        choices = c("AlzCol", "BouArm", "GirMar", "GirRin", "GueNic", "HooRol", "JonGeo", "LacEmm", "LecGer", "LecMar", "MolMar", "RosMar", "VarAla", "VirYve"),
                                        selected = "AlzCol"), 
                            # textOutput("aff_file1"),
                            # textOutput("aff_file2"),
      ), 
                     column(width = 6,
                            sliderInput(inputId = "immobility_threshold",
                                        label = "Immobility threshold",
                                        value = 0.67,
                                        min = 0.2,
                                        max = 0.7),
                            # textOutput("dimimmo"),
                            sliderInput(inputId = "no_labelled_threshold",
                                        label = "No labelled threshold",
                                        value = 0.5,
                                        min = 0.1,
                                        max = 0.7),
                            # textOutput("dimlab"),
                            sliderInput(inputId = "tree_number",
                                        label = "Tree number of the random forest",
                                        value = 700,
                                        min = 100,
                                        max = 1000),
                            ))),
  fluidRow(tabsetPanel(tabPanel("Data",
                                tabPanel("Obtained occurrences of labels",
                                         dataTableOutput("obtained_result")),
                                tabPanel("Mean absolute error",
                                         verbatimTextOutput("MAE"))),
                       tabPanel("Display",
                                navlistPanel(widths = c(12, 12),
                                             tabPanel("Resampling plot",
                                                       plotOutput("resampling_plot")),
                                             tabPanel("Plot of data without immobility data",
                                                       plotOutput("motion_plot")),
                                             tabPanel("Plot of labelled and no labelled data",
                                                       plotOutput("lab_no_lab_plot")),
                                             tabPanel("Plot of data associated with their label",
                                                       plotOutput("lab_plot"))))))
))
